export const QUERY_KEY = {
    // singup
    SING_UP: "SING_UP",
    // product
    GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
    GET_PRODUCT_BY_CATEGORY: "GET_PRODUCT_BY_CATEGORY",
    GET_FILTER_PRODUCT: "GET_FILTER_PRODUCT",
    GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
    GET_PRODUCT_NEW: "GET_PRODUCT_NEW",
    GET_PRODUCT_SALE: "GET_PRODUCT_SALE",
    GET_PRODUCT_DISCOUNT: "GET_PRODUCT_DISCOUNT",
    // cart
    GET_CART_BY_USER_ID: "GET_CART_BY_USER_ID",
    // order
    GET_ORDER_BY_USER_: "GET_ORDER_BY_USER_ID"
}